[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "mathics3_omnibus"
description = "A Collection Mathics3 components to provide the full Mathics3 experience"
dependencies = [
    "Mathics3[full] >= 10.0",
    "Mathics3-Frontend-django >= 10.0",
    "Mathics3_pygments >= 10.0",
    "Mathics3-Frontend-CLI[full] >= 10.0",
    "Mathics3-Module-nltk >= 10.0",
    "Mathics3-Module-PyICU >= 10.0",
    "Mathics3-Module-networkx >= 10.0",
]
requires-python = ">=3.11"
readme = "README.rst"
license = "GPL-3.0-or-later"
keywords = ["Mathematica", "Wolfram", "Interpreter", "Shell", "Math", "CAS"]
maintainers = [
    {name = "Mathics3 Group"},
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Interpreters",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://mathics.org/"

[tool.poetry]
include = ["script/dmathics3"]

[tool.setuptools]
script-files = [
    "script/dmathics3",
    "script/dmathics3-codeparser-parse",
    "script/dmathics3-codeparser-tokenize",
    "script/dmathics3copy",
    "script/dmathics3script",
    "script/dmathics3doc",
    "script/dMathics3Server",
    "script/term-background.sh",
]

[tool.setuptools.packages.find]
include = ["mathics3_omnibus*"]

[tool.setuptools.dynamic]
version = {attr = "mathics3_omnibus.version.__version__"}
